//! Golden tests against PyTorch references (issue #8).
//!
//! Each test loads a fixture generated by a `tools/gen_*_fixture.py`
//! script (committed under `tools/fixtures/`) and compares the Rust
//! implementation against the saved PyTorch output. Tests skip with a
//! message when their fixture is absent so the default suite stays green
//! before fixtures for heavyweight checkpoints are generated.

use std::collections::HashMap;
use std::path::PathBuf;

use candle_core::{forward_ad::jvp, Device, Tensor, Var, D};

fn fixture(name: &str) -> Option<HashMap<String, Tensor>> {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tools/fixtures")
        .join(name);
    if !path.exists() {
        eprintln!("skipping: fixture {name} not found — generate it with tools/gen_*_fixture.py");
        return None;
    }
    Some(candle_core::safetensors::load(&path, &Device::Cpu).unwrap())
}

fn max_abs_diff(a: &Tensor, b: &Tensor) -> f32 {
    (a - b)
        .unwrap()
        .abs()
        .unwrap()
        .max_all()
        .unwrap()
        .to_scalar()
        .unwrap()
}

/// Mirrors `f` in `tools/gen_jvp_fixture.py`: linear → silu → layernorm →
/// self-attention → residual → timestep modulation → tanh → linear.
fn mini_dit(w: &HashMap<String, Tensor>, x: &Tensor, t: &Tensor) -> candle_core::Result<Tensor> {
    let lin = |h: &Tensor, wname: &str, bname: &str| -> candle_core::Result<Tensor> {
        h.broadcast_matmul(&w[wname].t()?)?.broadcast_add(&w[bname])
    };
    let h = lin(x, "w1", "b1")?.silu()?;
    // Layer norm without affine, eps 1e-5.
    let mean = h.mean_keepdim(D::Minus1)?;
    let h = h.broadcast_sub(&mean)?;
    let var = h.sqr()?.mean_keepdim(D::Minus1)?;
    let h = h.broadcast_div(&(var + 1e-5)?.sqrt()?)?;

    let d_h = h.dim(D::Minus1)?;
    let q = lin(&h, "wq", "bq")?;
    let k = lin(&h, "wk", "bk")?;
    let v = lin(&h, "wv", "bv")?;
    let scores = (q.matmul(&k.transpose(1, 2)?.contiguous()?)? / (d_h as f64).sqrt())?;
    let a = candle_nn::ops::softmax(&scores, D::Minus1)?;
    let h = (h + a.matmul(&v)?)?;

    let (b, _, _) = h.dims3()?;
    let h = h.broadcast_mul(&(t + 1.0)?.reshape((b, 1, 1))?)?;
    lin(&h.tanh()?, "w2", "b2")
}

#[test]
fn jvp_matches_torch_func_jvp() {
    let Some(fx) = fixture("jvp.safetensors") else {
        return;
    };
    let x = Var::from_tensor(&fx["x"]).unwrap();
    let t = Var::from_tensor(&fx["t"]).unwrap();

    let y = mini_dit(&fx, x.as_tensor(), t.as_tensor()).unwrap();
    let forward_diff = max_abs_diff(&y, &fx["y_ref"]);
    assert!(
        forward_diff < 1e-5,
        "forward pass diverges from PyTorch: {forward_diff}"
    );

    let dy = jvp(
        &y,
        &[(x.as_tensor(), &fx["vx"]), (t.as_tensor(), &fx["vt"])],
    )
    .unwrap();
    let jvp_diff = max_abs_diff(&dy, &fx["jvp_ref"]);
    assert!(
        jvp_diff < 1e-4,
        "candle forward-AD JVP diverges from torch.func.jvp: {jvp_diff}"
    );
}
